### ISSUE TITLE
Everytime that i try to render I get a white screen & No entities in render

### ISSUE THREAD

**Issue by MoonstruckSpirit** [min2222/ReplayMod-Forge-Reborn#1]
I'm not running Rubidium, Oculus or any Shader
I do have them in the pack but with or without it happens.

Everytime I click render the screen just goes white. 
It will render but then all the entities are missing including the player entity.

https://streamable.com/mri8dc

Mod Version: replay-forge-1.19.2-1.0.5.
Modlist https://pastebin.com/qg5uURUm

**Comment by min2222** [comment]
sorry for late reply, but seems like video is archived, can you post new one?
