### ISSUE TITLE
Gamecrash with medieval mod 

### ISSUE THREAD

**Issue by Ernb4s** [min2222/ReplayMod-Forge-Reborn#2]
game crashing shortly after recording started. log attached
[2023-05-05-2.log](https://github.com/min2222/ReplayMod-Forge-Reborn/files/11408245/2023-05-05-2.log)

**Comment by min2222** [comment]
you should post a crash log or debug.log

**Comment by Ernb4s** [comment]
Hey I’m sorry, the cause for the crash wasn’t replay mod. I made a mistake and realized it two hours ago Have a nice daySent from my iPadOn 6. May 2023, at 07:14, min2222 ***@***.***> wrote:﻿
you should post a crash log or debug.log
